wget -O conllu/sst-test.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Slovenian-SST/master/sl_sst-ud-test.conllu
wget -O conllu/sst-train.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Slovenian-SST/master/sl_sst-ud-train.conllu
wget -O conllu/janes-train.conllu https://raw.githubusercontent.com/clarinsi/babushka-bench/master/datasets/sl/janes-tag/train.conllu
wget -O conllu/janes-test.conllu https://raw.githubusercontent.com/clarinsi/babushka-bench/master/datasets/sl/janes-tag/test.conllu
wget -O conllu/janes-dev.conlu https://raw.githubusercontent.com/clarinsi/babushka-bench/master/datasets/sl/janes-tag/dev.conllu
wget -O conllu/ssj500-train.conllu https://raw.githubusercontent.com/clarinsi/babushka-bench/master/datasets/sl/ssj500k/train.conllu
wget -O conllu/ssj500-dev.conllu https://raw.githubusercontent.com/clarinsi/babushka-bench/master/datasets/sl/ssj500k/dev.conllu
wget -O conllu/ssj500-test.conllu https://raw.githubusercontent.com/clarinsi/babushka-bench/master/datasets/sl/ssj500k/test.conllu
wget -O conllu/ssj-train.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Slovenian-SSJ/master/sl_ssj-ud-train.conllu
wget -O conllu/ssj-dev.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Slovenian-SSJ/master/sl_ssj-ud-dev.conllu
wget -O conllu/ssj-test.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_Slovenian-SSJ/master/sl_ssj-ud-test.conllu
